"""Added token

Revision ID: 8d8694f03fc4
Revises: a2a495c089e5
Create Date: 2024-11-09 11:56:53.621066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8694f03fc4'
down_revision = 'a2a495c089e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('token', sa.String(), nullable=False))
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_transactions_token'), 'transactions', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_token'), table_name='transactions')
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('transactions', 'token')
    # ### end Alembic commands ###
