"""Added paymentDetailsModel

Revision ID: b868e7426671
Revises: 8d8694f03fc4
Create Date: 2025-01-23 15:18:50.156641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b868e7426671'
down_revision = '8d8694f03fc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
